
package WebServices.UsuarioWS;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ExPaqueteNoActivado", targetNamespace = "http://WebServices/")
public class ExPaqueteNoActivado_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExPaqueteNoActivado faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ExPaqueteNoActivado_Exception(String message, ExPaqueteNoActivado faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ExPaqueteNoActivado_Exception(String message, ExPaqueteNoActivado faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: WebServices.UsuarioWS.ExPaqueteNoActivado
     */
    public ExPaqueteNoActivado getFaultInfo() {
        return faultInfo;
    }

}
