
package WebServices.UsuarioWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UsuarioWSService", targetNamespace = "http://WebServices/", wsdlLocation = "http://pcunix124:8280/usuarioWS?wsdl")
public class UsuarioWSService
    extends Service
{

    private final static URL USUARIOWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WebServices.UsuarioWS.UsuarioWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WebServices.UsuarioWS.UsuarioWSService.class.getResource(".");
            url = new URL(baseUrl, "http://pcunix124:8280/usuarioWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://pcunix124:8280/usuarioWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USUARIOWSSERVICE_WSDL_LOCATION = url;
    }

    public UsuarioWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioWSService() {
        super(USUARIOWSSERVICE_WSDL_LOCATION, new QName("http://WebServices/", "UsuarioWSService"));
    }

    /**
     * 
     * @return
     *     returns UsuarioWS
     */
    @WebEndpoint(name = "UsuarioWSPort")
    public UsuarioWS getUsuarioWSPort() {
        return super.getPort(new QName("http://WebServices/", "UsuarioWSPort"), UsuarioWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioWS
     */
    @WebEndpoint(name = "UsuarioWSPort")
    public UsuarioWS getUsuarioWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices/", "UsuarioWSPort"), UsuarioWS.class, features);
    }

}
