/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfirmarApuesta.java
 *
 * Created on 06/11/2011, 03:39:04 PM
 */

package dispositivomovil.Apuestas;

import WebServices.DispMovilWS.DataApuestaWS;
import WebServices.DispMovilWS.DispMovilWS;
import WebServices.DispMovilWS.DispMovilWSService;
import dispositivomovil.DispositivoMovil;
import dispositivomovil.MenuPrincipal;
import java.io.FileInputStream;
import java.net.UnknownHostException;
import java.util.Properties;
import javax.swing.ImageIcon;

/**
 *
 * @author gonzalo
 */
public class ConfirmarApuesta extends javax.swing.JPanel {

    /** Creates new form ConfirmarApuesta */
    public ConfirmarApuesta(DispositivoMovil m, DataApuestaWS dataAp, boolean agregarPaquete) {
        initComponents();
        this.dispMov = m;
        this.agregarPaquete = agregarPaquete;
        this.jLabelBeneficio.setText(Float.toString(dataAp.getBeneficio()));
        this.jLabelDividendo.setText(Float.toString(dataAp.getDividendo()));
        this.jLabelMonto.setText(Float.toString(dataAp.getMonto()));
        this.jLabelSaldoNuevo.setText(Float.toString(dataAp.getSaldoNuevo()));
        this.setOpaque(false);
        this.jLabelError.setText("");

        ImageIcon ic2 = new ImageIcon("images/aceptar.png");
        ImageIcon im2 = new ImageIcon(ic2.getImage().getScaledInstance(15,15,15));
        this.jButton1.setIcon(im2);

        ImageIcon ic = new ImageIcon("images/x.png");
        ImageIcon im = new ImageIcon(ic.getImage().getScaledInstance(15,15,15));
        this.jButton2.setIcon(im);

    }

    void apostar(boolean ok, boolean paquete) {
        try {
            Properties prop = new Properties();
            FileInputStream fis = new FileInputStream("web_services.xml");
            prop.loadFromXML(fis);
            String dir = prop.getProperty("dir_publicar");

            DispMovilWSService dms = new DispMovilWSService(new java.net.URL("http://"+dir+":8280/dispMovilWS?wsdl"),new javax.xml.namespace.QName("http://WebServices/", "DispMovilWSService"));

            DispMovilWS disp = dms.getDispMovilWSPort();

            if (this.agregarPaquete){
                if (ok)
                    disp.agregarApuestaPaquete(this.dispMov.nickUsuLogueado);
            }
            else
                disp.confirmarAltaApuesta(this.dispMov.nickUsuLogueado, ok, false);

            MenuPrincipal menu = new MenuPrincipal(this.dispMov);
            this.dispMov.jDesktopPane1.add(menu);
            menu.setVisible(true);
            menu.setSize(320, 420);
            this.removeAll();
            this.dispMov.jDesktopPane1.remove(this);

        }
        catch (Exception exc) {
            if (exc.getMessage().contains("WSDL")) {
                dispMov.online = false;
                ImageIcon imIcon= new ImageIcon("images/desconectado.png");
                this.dispMov.jLabel1.setIcon(new ImageIcon(imIcon.getImage().getScaledInstance(20,20,20)));
                dispMov.timer.start();
                this.jLabelError.setText("Error: Se perdio la conexion");
            }else{
                this.jLabelError.setText("Error: "+exc.getMessage());
            }
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDividendo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jLabelBeneficio = new javax.swing.JLabel();
        jLabelSaldoNuevo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desea confirmar la apuesta?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dividendo:");

        jLabelDividendo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDividendo.setText("jLabel6");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monto: ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Beneficio: ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo nuevo: ");

        jLabelMonto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonto.setText("jLabel5");

        jLabelBeneficio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBeneficio.setText("jLabel6");

        jLabelSaldoNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoNuevo.setText("jLabel7");

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.darkGray);
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDividendo)
                                    .addComponent(jLabelBeneficio)
                                    .addComponent(jLabelSaldoNuevo)
                                    .addComponent(jLabelMonto)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelError)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelMonto))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelDividendo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelBeneficio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelSaldoNuevo))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabelError)
                .addGap(34, 34, 34))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!this.dispMov.online) {
            this.jLabelError.setText("Error: Sin conexion");
        }else {
            this.apostar(true,this.agregarPaquete);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!this.dispMov.online) {
            this.jLabelError.setText("Error: Sin conexion");
        }else {
            this.apostar(false,this.agregarPaquete);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBeneficio;
    private javax.swing.JLabel jLabelDividendo;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelSaldoNuevo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private DispositivoMovil dispMov;
    private boolean agregarPaquete;
}
