/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Partidos.java
 *
 * Created on Nov 3, 2011, 5:09:00 PM
 */

package dispositivomovil.Apuestas;

import WebServices.DispMovilWS.DataApuestaWS;
import WebServices.DispMovilWS.DataPartido;
import WebServices.DispMovilWS.DataPartido.GolesDivs;
import WebServices.DispMovilWS.DispMovilWS;
import WebServices.DispMovilWS.DispMovilWSService;
import WebServices.DispMovilWS.TipoCampeonatoApuesta;
import WebServices.DispMovilWS.TipoCompeticion;
import WebServices.DispMovilWS.TipoDividendo;
import dispositivomovil.DispositivoMovil;
import java.io.FileInputStream;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.xml.namespace.QName;

/**
 *
 * @author tprog084
 */
public class Partidos extends javax.swing.JPanel {

    /** Creates new form Partidos */
    public Partidos(DispositivoMovil dispMov ,int idComp, List<DataPartido> partidos) {

        initComponents();

        this.dispMov = dispMov;
        this.setOpaque(false);
        this.dispMov.botonAtras.setEnabled(true);
        this.partidos = partidos;
        this.jLabelError.setText("");
        this.idComp = idComp;
        this.jButton1.setEnabled(false);
        this.jButton2.setEnabled(false);

        List<DataPartido> noFinalizados = new ArrayList<DataPartido>();
        
        for (int i=0; i<partidos.size(); i++) {
            if (!partidos.get(i).isEstaFinalizado()){
                noFinalizados.add(partidos.get(i));
                System.out.print(i);
            }       
        }

        String [] objs = new String[noFinalizados.size()];
        
        for (int i=0; i<noFinalizados.size(); i++) {
            objs[i] = noFinalizados.get(i).getDataInfoPart().getNomLocal() + " Vs " + noFinalizados.get(i).getDataInfoPart().getNomVisita();
        }

        this.jList2.setListData(objs);

        ImageIcon ic = new ImageIcon("images/carrito.png");
        ImageIcon im = new ImageIcon(ic.getImage().getScaledInstance(15,15,15));

        this.jButton2.setIcon(im);

        ImageIcon ic2 = new ImageIcon("images/ap.png");
        ImageIcon im2 = new ImageIcon(ic2.getImage().getScaledInstance(15,15,15));
        this.jButton1.setIcon(im2);

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tmonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        botonres = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione un Partido");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 270, 15);

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Apostar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 350, 130, 25);

        jButton2.setBackground(java.awt.Color.darkGray);
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Paquete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(180, 350, 130, 25);

        tmonto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tmonto.setForeground(new java.awt.Color(255, 255, 255));
        tmonto.setText("ingrese monto");
        tmonto.setOpaque(false);
        tmonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmontoMouseClicked(evt);
            }
        });
        tmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmontoActionPerformed(evt);
            }
        });
        tmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tmontoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tmontoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tmontoKeyReleased(evt);
            }
        });
        add(tmonto);
        tmonto.setBounds(20, 310, 107, 19);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("x 1.0 =");
        add(jLabel2);
        jLabel2.setBounds(140, 310, 50, 15);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel3);
        jLabel3.setBounds(210, 310, 100, 20);

        jScrollPane2.setOpaque(false);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setOpaque(false);
        jList1.setSelectionBackground(new java.awt.Color(0, 153, 204));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 240, 250, 60);

        buttonGroup1.add(botonres);
        botonres.setSelected(true);
        botonres.setText("Res");
        botonres.setOpaque(false);
        botonres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonresMouseClicked(evt);
            }
        });
        add(botonres);
        botonres.setBounds(70, 190, 60, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Res Exacto");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        add(jRadioButton2);
        jRadioButton2.setBounds(120, 190, 110, 23);

        jScrollPane1.setOpaque(false);

        jList2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jList2.setForeground(java.awt.Color.darkGray);
        jList2.setOpaque(false);
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList2);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 250, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo");
        add(jLabel4);
        jLabel4.setBounds(30, 190, 240, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dividendos");
        add(jLabel5);
        jLabel5.setBounds(30, 220, 120, 15);

        jLabelError.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("jLabel6");
        add(jLabelError);
        jLabelError.setBounds(10, 390, 300, 15);
    }// </editor-fold>//GEN-END:initComponents

    private void tmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmontoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tmontoActionPerformed

    private void tmontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmontoMouseClicked
        // TODO add your handling code here:
        tmonto.setText("");
    }//GEN-LAST:event_tmontoMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
       if (fila>=0){
            this.Seleccionado = this.jList1.getSelectedIndex();
           DataPartido data = partidos.get(fila);

           if (this.botonres.isSelected()) {
               div = 0;
               if (Seleccionado == 0)
                   div = data.getDividendos().getDividendoLocal();
               else if (Seleccionado==1)
                   div = data.getDividendos().getDividendoEmpate();
               else
                   div = data.getDividendos().getDividendoVisita();
           } else {
                div = data.getGolesDivs().getEntry().get(this.Seleccionado).getValue();
           }


           jLabel2.setText("x "+Float.toString(div) + "=");

           try {
               float a;
               a = Float.valueOf(this.tmonto.getText());
               a = a*div;
                jLabel3.setText(Float.toString(a));
           }catch(Exception e){
                jLabel3.setText("");
           }

           if (fila!=-1 && this.Seleccionado>=0) {
               this.jButton1.setEnabled(true);
               this.jButton2.setEnabled(true);
            }
        }


    }//GEN-LAST:event_jList1MouseClicked

    private void tmontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmontoKeyTyped
        // TODO add your handling code here:

       try {
           float a;
           a = Float.valueOf(this.tmonto.getText());
           a = a*div;
            jLabel3.setText(Float.toString(a));
       }catch(Exception e){
            jLabel3.setText("Nan");
       }
    }//GEN-LAST:event_tmontoKeyTyped

    private void tmontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmontoKeyPressed
        // TODO add your handling code here:
        try {
           float a;
           a = Float.valueOf(this.tmonto.getText());
           a = a*div;
            jLabel3.setText(Float.toString(a));
       }catch(Exception e){
            jLabel3.setText("Nan");
       }
    }//GEN-LAST:event_tmontoKeyPressed

    private void botonresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonresMouseClicked
        // TODO add your handling code here:
        if (fila>=0){
            DataPartido data = partidos.get(fila);
            String [] str = new String[3];

            str[0] = data.getDataInfoPart().getNomLocal()+ "        " + Float.toString(data.getDividendos().getDividendoLocal());
            str[1] = "X"+ "        " + Float.toString(data.getDividendos().getDividendoEmpate());
            str[2] = data.getDataInfoPart().getNomVisita()+ "        " + Float.toString(data.getDividendos().getDividendoVisita());

            this.jList1.setListData(str);
        }
    }//GEN-LAST:event_botonresMouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        if (fila>=0){
            DataPartido data = partidos.get(fila);
            GolesDivs golesDiv = data.getGolesDivs();
            dividendos =  golesDiv.getEntry();
            String [] str = new String[dividendos.size()];

            for (int i=0; i<dividendos.size(); i++){
                GolesDivs.Entry gol = (GolesDivs.Entry) dividendos.get(i);
                str[i] = Integer.toString(gol.getKey().getGolesLocal())+"x"+Integer.toString(gol.getKey().getGolesVisita())+"       "+Float.toString(gol.getValue());
            }
            this.jList1.setListData(str);
        }
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void apostarPartidoAux(boolean paquete) {
        String dir;
        // TODO add your handling code here:
        
        try {
            //apuesta res comun
            Properties prop = new Properties();
            FileInputStream stream;
            stream = new FileInputStream("web_services.xml");
            prop.loadFromXML(stream);
            dir = prop.getProperty("dir_publicar");
            DispMovilWSService serv = new DispMovilWSService(new URL("http://" + dir + ":8280/dispMovilWS?wsdl"), new QName("http://WebServices/", "DispMovilWSService"));
            DispMovilWS proxy = serv.getDispMovilWSPort();

            TipoCampeonatoApuesta tipoCampAp = null;
            if (this.botonres.isSelected()){
                tipoCampAp = TipoCampeonatoApuesta.PARTIDO;
            } else {
                tipoCampAp = TipoCampeonatoApuesta.RES_EXACTO;
            }

            proxy.seleccionarCampApuesta(this.dispMov.nickUsuLogueado, tipoCampAp);
            
            if (proxy.verInfoCompeticion(this.dispMov.nickUsuLogueado, this.idComp).getTipo()!=TipoCompeticion.PARTIDO_INDIVIDUAL) {
                proxy.seleccionarPartidoCamp(this.dispMov.nickUsuLogueado, this.partidos.get(fila).getDataInfoPart().getIdPar());
            }

            if (this.botonres.isSelected()){
                TipoDividendo tipoD = null;
                if (this.Seleccionado==0) {
                    tipoD = TipoDividendo.LOCAL;
                } else if (this.Seleccionado==1) {
                    tipoD = TipoDividendo.EMPATE;
                } else {
                    tipoD = TipoDividendo.VISITANTE;
                }

                if (!paquete)
                    proxy.apostarPartido(this.dispMov.nickUsuLogueado,tipoD, Float.parseFloat(this.tmonto.getText()));
                else
                    proxy.apostarPartidoPaquete(this.dispMov.nickUsuLogueado,tipoD, Float.parseFloat(this.tmonto.getText()));

            } else {
                int golL = this.partidos.get(this.fila).getGolesDivs().getEntry().get(this.Seleccionado).getKey().getGolesLocal();
                int golV = this.partidos.get(this.fila).getGolesDivs().getEntry().get(this.Seleccionado).getKey().getGolesVisita();

                if (!paquete)
                    proxy.apostarResultadoExacto(this.dispMov.nickUsuLogueado,golL,golV,Float.parseFloat(this.tmonto.getText()));
                else
                    proxy.apostarResultadoExactoPaquete(this.dispMov.nickUsuLogueado,golL,golV,Float.parseFloat(this.tmonto.getText()));

            }
            
            DataApuestaWS da = null;
            if (!paquete)
                da = proxy.mostrarApuesta(this.dispMov.nickUsuLogueado);
            else
                da = proxy.mostrarApuestaPaquete(this.dispMov.nickUsuLogueado);

            ConfirmarApuesta c = new ConfirmarApuesta(this.dispMov,da,paquete);
            c.setSize(320,420);
            this.dispMov.jDesktopPane1.add(c);
            c.setVisible(true);

            this.dispMov.jDesktopPane1.remove(this);
            this.removeAll();
        }
        catch (NumberFormatException e){
            this.jLabelError.setText("Error: Monto invalido");
        }
        catch (Exception ex) {
            if (ex.getMessage().contains("WSDL")) {
                // Error de conexion
                this.jLabelError.setText("Error: Conexion perdida");
                dispMov.online = false;
                ImageIcon imIcon= new ImageIcon("images/desconectado.png");
                this.dispMov.jLabel1.setIcon(new ImageIcon(imIcon.getImage().getScaledInstance(20,20,20)));
                dispMov.timer.start();
            }else {
                this.jLabelError.setText("Error:"+ex.getMessage());
            }
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!this.dispMov.online){
            this.jLabelError.setText("Error: Sin conexion");
        }else{
            this.apostarPartidoAux(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!this.dispMov.online){
            this.jLabelError.setText("Error: Sin conexion");
        }else{
            this.apostarPartidoAux(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tmontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmontoKeyReleased
        // TODO add your handling code here:
        try {
           float a;
           a = Float.valueOf(this.tmonto.getText());
           a = a*div;
            jLabel3.setText(Float.toString(a));
       }catch(Exception e){
            jLabel3.setText("Nan");
       }
    }//GEN-LAST:event_tmontoKeyReleased

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:

        fila = jList2.getSelectedIndex();

        //vemos si la apuesta de de un tipo o de otro
        //armamos la lista
        try {
            DataPartido data = partidos.get(fila);

            if (this.botonres.isSelected()) {
                String [] str = new String[3];

                str[0] = data.getDataInfoPart().getNomLocal()+ "        " + Float.toString(data.getDividendos().getDividendoLocal());
                str[1] = "X"+ "        " + Float.toString(data.getDividendos().getDividendoEmpate());
                str[2] = data.getDataInfoPart().getNomVisita()+ "        " + Float.toString(data.getDividendos().getDividendoVisita());

                this.jList1.setListData(str);
            } else {

                GolesDivs golesDiv = data.getGolesDivs();
                dividendos =  golesDiv.getEntry();
                String [] str = new String[dividendos.size()];

                for (int i=0; i<dividendos.size(); i++){
                    GolesDivs.Entry gol = (GolesDivs.Entry) dividendos.get(i);
                    str[i] = Integer.toString(gol.getKey().getGolesLocal())+"x"+Integer.toString(gol.getKey().getGolesVisita())+"       "+Float.toString(gol.getValue());
                }
                this.jList1.setListData(str);
            }
        }
        catch (Exception exc){
            System.out.println("BIEN!!");
        }


    }//GEN-LAST:event_jList2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonres;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tmonto;
    // End of variables declaration//GEN-END:variables
    public DispositivoMovil dispMov;
    private int idComp;
    private List<DataPartido> partidos;
    private int Seleccionado;

    private int fila = -1;
    private float div = 1;
    private List dividendos;

   
}
