/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VerPaquete.java
 *
 * Created on Nov 9, 2011, 5:01:36 PM
 */

package dispositivomovil.Apuestas;   

import dispositivomovil.DispositivoMovil;
import WebServices.DispMovilWS.DataApuestaWS;
import WebServices.DispMovilWS.DataPaqueteApuestasWS;
import WebServices.DispMovilWS.DispMovilWS;
import WebServices.DispMovilWS.DispMovilWSService;
import WebServices.DispMovilWS.TipoDividendo;
import dispositivomovil.MenuPrincipal;
import java.io.FileInputStream;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.List;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.xml.namespace.QName;



/**
 *
 * @author tprog081
 */
public class VerPaquete extends javax.swing.JPanel {

    /** Creates new form VerPaquete */
    public VerPaquete(DispositivoMovil disp, DataPaqueteApuestasWS paq) {
        initComponents();
        this.setOpaque(false);
        this.dispMov = disp;
        this.dispMov.botonAtras.setEnabled(true);
        this.jLabel1.setText("");

        List<DataApuestaWS> apuestasPaq = paq.getApuestas();
        String [] str = new String[apuestasPaq.size()];

        for (int i=0; i<apuestasPaq.size(); i++) {
            String nomComp = "";
            String monto = Float.toString(apuestasPaq.get(i).getMonto());
            String div = Float.toString(apuestasPaq.get(i).getDividendo());
            String tipo="";
            String resto = "";

            if (apuestasPaq.get(i).getTipo()==0) {
                nomComp = apuestasPaq.get(i).getCompeticion().getNombre();
                tipo = "Campeon";
                resto = apuestasPaq.get(i).getEquipo().getNombre();
            } else if (apuestasPaq.get(i).getTipo()==1) {
                nomComp=apuestasPaq.get(i).getPartido().getDataInfoPart().getNomComp();
                tipo = "Res Exacto";
                resto = "Res:"+apuestasPaq.get(i).getGolesL()+"x"+apuestasPaq.get(i).getGolesV()+" "+
                        apuestasPaq.get(i).getPartido().getDataInfoPart().getNomLocal()+"-"+apuestasPaq.get(i).getPartido().getDataInfoPart().getNomVisita();
            } else if (apuestasPaq.get(i).getTipo()==2) {
                nomComp = apuestasPaq.get(i).getCompeticion().getNombre();
                tipo = "Goleador";
                resto=  apuestasPaq.get(i).getJugador().getNombre();

            } else if (apuestasPaq.get(i).getTipo()==3) {
                nomComp=apuestasPaq.get(i).getPartido().getDataInfoPart().getNomComp();
                tipo = "Partido";
                String tipoRes = "";
                if (apuestasPaq.get(i).getTipoResultado()==TipoDividendo.LOCAL)
                    tipoRes="Local";
                else if (apuestasPaq.get(i).getTipoResultado()==TipoDividendo.EMPATE)
                    tipoRes="Empate";
                else
                    tipoRes="Visitante";

                resto = "Res:"+tipoRes+" "+ apuestasPaq.get(i).getPartido().getDataInfoPart().getNomLocal()+"-"+
                        apuestasPaq.get(i).getPartido().getDataInfoPart().getNomVisita();
            }
            String saltoLinea = System.getProperty("line.separator");
            str[i] =tipo+saltoLinea+
                    nomComp+saltoLinea+
                    resto+saltoLinea+
                    "Monto:"+monto+saltoLinea+
                    "Dividendo:"+div;
        }

        jList1.setListData(str); 
        jList1.setCellRenderer(new MiRendererDeLista());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apuestas del Paquete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jScrollPane1.setOpaque(false);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setOpaque(false);
        jScrollPane1.setViewportView(jList1);

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar Paquete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.dispMov.online && !this.dispMov.nickUsuLogueado.equals("")) {
            // Tengo conexion
            try {
                Properties prop = new Properties();
                FileInputStream stream = new FileInputStream("web_services.xml");
                prop.loadFromXML(stream);
                String dir = prop.getProperty("dir_publicar");

                DispMovilWSService serv = new DispMovilWSService(new URL("http://"+dir+":8280/dispMovilWS?wsdl"),
                        new QName("http://WebServices/","DispMovilWSService"));

                DispMovilWS proxy = serv.getDispMovilWSPort();

                boolean valido = proxy.validarPaqueteApuestas(this.dispMov.nickUsuLogueado);
                
                if (valido)
                    proxy.confirmarPaqueteApuestas(this.dispMov.nickUsuLogueado);
                else {
                    this.jLabel1.setText("Error: Paquete invalido");
                    this.jButton1.setEnabled(false);
                    return;
                }

                this.jLabel1.setText("Exito: Se confirmo el paquete");
                this.jButton1.setEnabled(false);
                
            }
            catch (Exception exc) {
                if (exc.getMessage().contains("WSDL")) {
                    // Hubo error de conexion
                    this.jLabel1.setText("Error: Se ha perdido la conexion");
                    this.dispMov.online=false;
                    ImageIcon imIcon= new ImageIcon("images/desconectado.png");
                    this.dispMov.jLabel1.setIcon(new ImageIcon(imIcon.getImage().getScaledInstance(20,20,20)));
                    ((DispositivoMovil)(this.dispMov)).timer.start();
                } else {
                    this.jLabel1.setText("Error: "+exc.getMessage());
                    this.jButton1.setEnabled(false);
                }
            }

        } else {
            this.jLabel1.setText("Error: Sin conexion");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private DispositivoMovil dispMov; 
}

