/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TablaPenca.java
 *
 * Created on Nov 3, 2011, 4:37:05 PM
 */

package dispositivomovil.Pencas;


import WebServices.DispMovilWS.DataInfoPenca;
import WebServices.DispMovilWS.DataInfoUsuarioPenca;
import WebServices.DispMovilWS.DispMovilWS;
import WebServices.DispMovilWS.DispMovilWSService;
import dispositivomovil.DispositivoMovil;
import dispositivomovil.objetos.Competicion;
import dispositivomovil.objetos.Penca;
import dispositivomovil.objetos.PosicionPenca;
import java.io.FileInputStream;
import java.util.List;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tprog084
 */
public class TablaPenca extends javax.swing.JPanel {

    /** Creates new form TablaPenca */
    public TablaPenca(JFrame m, int idPenca) {
        initComponents();

        this.setSize(320,420);
        this.dispMov = (DispositivoMovil) m;
        DataInfoPenca dip = null;
        String [] s = {"Nick","Puntos"};
        this.jLabelError.setVisible(false);

        if(this.dispMov.online){
            try{

                    
                    Properties prop = new Properties();
                    FileInputStream fis = new FileInputStream("web_services.xml");
                    prop.loadFromXML(fis);
                    String dir = prop.getProperty("dir_publicar");

                    DispMovilWSService dms = new DispMovilWSService(new java.net.URL("http://"+dir+":8280/dispMovilWS?wsdl"),new javax.xml.namespace.QName("http://WebServices/", "DispMovilWSService"));
                    DispMovilWS disp = dms.getDispMovilWSPort();
                    dip = disp.verTablaPosicionesPenca(this.dispMov.nickUsuLogueado, idPenca);

                    List<DataInfoUsuarioPenca> lista = dip.getTablaPosiciones();

                    Object[][] tabla = new Object[lista.size()][2];
                    for (int i =0;i< lista.size();i++) {
                         tabla[i][0]= lista.get(i).getNick();
                          tabla[i][1]= lista.get(i).getPuntos();
                     }
                    TableModel dtm = new DefaultTableModel(tabla,s);
                    this.tablaPos.setModel(dtm);

                     jLabel3.setText(Float.toString(dip.getPozo()));

          }catch(Exception e){

                this.jLabelError.setText("Error: Se perdio la conexion");
                dispMov.online = false;
                ImageIcon imIcon= new ImageIcon("images/desconectado.png");
                this.dispMov.jLabel1.setIcon(new ImageIcon(imIcon.getImage().getScaledInstance(20,20,20)));
                dispMov.timer.start();

                 Penca p = this.dispMov.em.find(Penca.class, ((Competicion)this.dispMov.em.find(Competicion.class, idPenca)).getPenca().getId());
                List<PosicionPenca> pos = p.getPos();
                Object[][] tabla = new Object[pos.size()][2];
                for (int i =0;i< pos.size();i++) {
                tabla[i][0]= pos.get(i).getNick();
                tabla[i][1]= pos.get(i).getPuntos();
                        }
                TableModel dtm = new DefaultTableModel(tabla,s);
                this.tablaPos.setModel(dtm);

                jLabel3.setText(Float.toString(p.getPozo()));

        }

        }else{
             Penca p= this.dispMov.em.find(Penca.class, ((Competicion)this.dispMov.em.find(Competicion.class, idPenca)).getPenca().getId());
             List<PosicionPenca> pos = p.getPos();
            Object[][] tabla = new Object[pos.size()][2];
            for (int i =0;i< pos.size();i++) {
            tabla[i][0]= pos.get(i).getNick();
            tabla[i][1]= pos.get(i).getPuntos();
                    }
            TableModel dtm = new DefaultTableModel(tabla,s);
            this.tablaPos.setModel(dtm);

            jLabel3.setText(Float.toString(p.getPozo()));
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(320, 420));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabla Posiciones");

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 255));

        tablaPos.setBackground(new java.awt.Color(204, 255, 255));
        tablaPos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPos.setRowSelectionAllowed(false);
        tablaPos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tablaPos.setShowHorizontalLines(false);
        tablaPos.setShowVerticalLines(false);
        tablaPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPos);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pozo Actual :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jLabelError.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabelError)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(87, 87, 87)
                .addComponent(jLabelError)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaPosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPos;
    // End of variables declaration//GEN-END:variables

   private DispositivoMovil dispMov;
}
