

package Formularios;
import Interface.*;
import DataTypes.*;
import java.util.List;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.JDesktopPane;

public class AltaLlave extends javax.swing.JInternalFrame {

    /** Creates new form AltaLlave */
    public AltaLlave(Tarea1 parent, List<DataIdNombre> lista, IControladorCompeticiones icc) {
        initComponents();

        this.icCompeticiones = icc;

        this.parent = parent;
        parent.setModoActivado(false);//no hace falta

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);

        setVisible(true);
        cargarListaCopas(lista);
    }

     private void cargarListaCopas(List<DataIdNombre> lista){
                String[] columnas = {"Id", "Nombre"};


                Iterator<DataIdNombre> it = lista.iterator();
                Object[][] data= new Object[lista.size()][2];

                for (int i = 0;i<lista.size();i++){
                     DataIdNombre c = (DataIdNombre) lista.get(i);
                     data[i][0] = c.getId();
                     data[i][1] = c.getNombre();
                }
                TableModel model = new DefaultTableModel(data,columnas);

                tablaCopas.setModel(model);
                final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);
                tablaCopas.setRowSorter(sorter);
                
                filtro.addKeyListener(new KeyListener() {
                    @Override
                    public void keyTyped(KeyEvent arg0) {
                        String i = "(?i)";
                        String texto = i.concat(filtro.getText());
                        if (texto.length() == 4) {
                            sorter.setRowFilter(null);
                        } else {
                            sorter.setRowFilter(RowFilter.regexFilter(texto));
                        }
                    }
                    @Override
                    public void keyReleased(KeyEvent arg0) {
                        String i = "(?i)";
                        String texto = i.concat(filtro.getText());
                        if (texto.length() == 4) {
                            sorter.setRowFilter(null);
                        } else {
                            sorter.setRowFilter(RowFilter.regexFilter(texto));
                        }
                    }
                    @Override
                    public void keyPressed(KeyEvent arg0) {
                        String i = "(?i)";
                        String texto = i.concat(filtro.getText());
                        if (texto.length() == 0) {
                                sorter.setRowFilter(null);
                            } else {
                                sorter.setRowFilter(RowFilter.regexFilter(texto));
                            }
                    }
           });

     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCopas = new javax.swing.JTable();
        filtro = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setTitle("Seleccionar Copa");

        tablaCopas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCopas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCopasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCopas);

        filtro.setText("buscar");
        filtro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtroMouseClicked(evt);
            }
        });

        jToggleButton1.setText("Siguiente");
        jToggleButton1.setEnabled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jToggleButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtroMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_filtroMouseClicked

    private void tablaCopasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCopasMouseClicked


        fila = tablaCopas.rowAtPoint(evt.getPoint());
        columna = tablaCopas.columnAtPoint(evt.getPoint());

        if ((fila > -1) && (columna > -1)){
            indiceSeleccionado  = (Integer) tablaCopas.getValueAt(fila,0);
            nombreCopa = (String) tablaCopas.getValueAt(fila,1);
            idCopa=(Integer)tablaCopas.getValueAt(fila,0);
            jToggleButton1.setEnabled(true);
        }


}//GEN-LAST:event_tablaCopasMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

            javax.swing.JInternalFrame i = new IngresoNombreLlave(idCopa,this.parent,icCompeticiones);
            parent.getLayeredPane().add(i);
            i.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
            //Fabrica f =  new Fabrica();
            parent.setModoActivado(true);
            //iCC= f.getIControladorCompeticiones();
            icCompeticiones.limpiarMemoriaAuxiliar();
            this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filtro;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable tablaCopas;
    // End of variables declaration//GEN-END:variables
    private int fila,columna,indiceSeleccionado,idCopa;
    private String nombreCopa;
    private Tarea1 parent;

    private IControladorCompeticiones icCompeticiones;
}
