/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaEquipo.java
 *
 * Created on 23/08/2011, 10:11:36 PM
 */

package Formularios;

/**
 *
 * @author santiago
 */
import javax.swing.JOptionPane;
import Interface.Fabrica;
import Interface.IControladorEquipos;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.ImageIcon;

public class AltaEquipo extends javax.swing.JInternalFrame {

    /** Creates new form AltaEquipo */
    public AltaEquipo(Tarea1 parent) {
        initComponents();

        this.parent = parent;
        parent.setModoActivado(false);//no hace falta

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        tNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Nuevo Equipo");

        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setPreferredSize(new java.awt.Dimension(128, 128));

        jButton6.setText("Cargar foto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tNombre.setColumns(22);
        tNombre.setMinimumSize(new java.awt.Dimension(100, 27));
        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addGap(21, 21, 21)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public String abrirImagen(JLabel label){
            JFileChooser chooser = new JFileChooser();
            chooser.setMultiSelectionEnabled(false);
            chooser.setFileFilter(new FiltroImagen());
            chooser.setAcceptAllFileFilterUsed(false);
            int e = chooser.showOpenDialog(null);

            String path = "";
            if (e == JFileChooser.APPROVE_OPTION){
                if (chooser.getSelectedFile() != null) {
                    path = chooser.getSelectedFile().getPath();
                    ImageIcon image = new ImageIcon(path);
                    label.setText("");
                    if(image.getIconHeight()>128 || image.getIconWidth()>128){
                        int a = image.getIconWidth()-128;
                        int b = image.getIconHeight() - 128;
                        int razon = a ;
                        if (a < b)
                            razon = b;
                        ImageIcon imageScalada = new ImageIcon(image.getImage().getScaledInstance(image.getIconWidth()-razon, image.getIconHeight()-razon, 128));

                        label.setIcon(imageScalada);
                    }else{
                       label.setIcon(image);
                    }
                }
            }
            return path;
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        pathImage = abrirImagen(jLabel12);
}//GEN-LAST:event_jButton6ActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //akta equipo>>
        Fabrica f =  new Fabrica();
        IControladorEquipos iCE = f.getIControladorEquipos();

        String entrada = tNombre.getText();
        //llamamos a la operacion de sistema, controlamos alguna excepcion con try
        if (entrada.isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: nombre de equipo vacio","Alta de Equipo", JOptionPane.ERROR_MESSAGE );
        } else{
            parent.setModoActivado(true);
            try{
                int id = iCE.darAltaEquipo(entrada,pathImage);//op de sistema
                String salida = Integer.toString(id);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Se ha creado el equipo de id = "+ salida,"Alta de Equipo", JOptionPane.INFORMATION_MESSAGE );
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Se ha producido un error en el Sistema","Alta de Equipo", JOptionPane.ERROR_MESSAGE );
            }
            this.dispose();

        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        parent.setModoActivado(true);
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
    private String pathImage = "";
    private Tarea1 parent;
}
