/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AsignarDividendos.java
 *
 * Created on Aug 24, 2011, 11:05:15 AM
 */

package Formularios;
import Interface.Fabrica;
import Interface.IControladorCompeticiones;
import javax.swing.JOptionPane;
import Excepciones.ExNoExisteCompeticion;
import Excepciones.ExDividendosYaAsignados;
import Excepciones.ExDividendosInvalidos;
import Excepciones.ExNoExistePartidoEnCompeticion;
/**
 *
 * @author tprog084
 */
public class AsignarDividendos extends javax.swing.JInternalFrame {

    /** Creates new form AsignarDividendos */
    public AsignarDividendos(int idComp, int idPart,Tarea1 parent, IControladorCompeticiones icce) {
        
        initComponents();
        this.idPart= idPart;
        this.idComp= idComp;
        
        this.icc = icce;
        this.parent = parent;
        buttonExacto.setName("botonExacto");
        
        
        parent.setModoActivado(false);//no hace falta
        

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton27 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        buttonExacto = new javax.swing.JButton();

        setTitle("Asignar Dividendos A Partido");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jButton27.setText("Cancelar");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jLabel55.setText("Dividendo Local");

        jLabel56.setText("Dividendo Empate");

        jButton26.setText("Aceptar");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jTextField3.setColumns(5);

        jLabel57.setText("Dividendo Visitante");

        jTextField5.setColumns(5);

        jTextField4.setColumns(5);

        buttonExacto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonExacto.setText("Incluir dividendos a resultado exacto");
        buttonExacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56)
                            .addComponent(jLabel57))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addComponent(buttonExacto)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(399, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton26)
                        .addGap(18, 18, 18)
                        .addComponent(jButton27)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExacto))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton26)
                    .addComponent(jButton27))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        Fabrica f = new Fabrica();
        float divL =0;
        float divE =0;
        float divV=0;
        boolean error = false;

        

        try {
            divL = Float.valueOf(jTextField3.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingreso Invalido: Ingrese Dividendo Local", "ERROR",JOptionPane.ERROR_MESSAGE);
            error = true;
            jTextField3.setText("");
        }
        try {
            divE = Float.valueOf(jTextField4.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingreso Invalido: Ingrese Dividendo Empate", "ERROR",JOptionPane.ERROR_MESSAGE);
            error = true;
            jTextField4.setText("");
        }
        try {
            divV = Float.valueOf(jTextField5.getText());

        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingreso Invalido: Ingrese Dividendo Visitante", "ERROR",JOptionPane.ERROR_MESSAGE);
            error = true;
            jTextField5.setText("");
        }

       if(!error) {
        try {
            icc.asignarDividendos(idPart, idComp, divL, divV, divE);
            icc.mailPartidoApostable(idPart, idComp,divL,divV,divE);//noviembre
            icc.asignarDividendoPartidoResultado(idPart, idComp);
            
            parent.setModoActivado(true);
            this.dispose();
           JOptionPane.showMessageDialog(null, "Se han asignados los Dividendos al Partido","Asignar Dividendos",JOptionPane.INFORMATION_MESSAGE);
           
        }catch (ExNoExisteCompeticion e){
              
              JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        catch (ExNoExistePartidoEnCompeticion e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        catch (ExDividendosYaAsignados e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        catch (ExDividendosInvalidos e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception e){
            System.out.println(e.getMessage()); 
        }
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        parent.setModoActivado(true);
        icc.limpiarMemoriaDivs();
        this.dispose();
       
    }//GEN-LAST:event_jButton27ActionPerformed

private void buttonExactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExactoActionPerformed

        if (!icc.getDivsResultsAsignados()){
            javax.swing.JInternalFrame it = new DivsResultadoExacto(this.parent,0,0,idPart,idComp,true,icc);
            this.parent.getLayeredPane().add(it);

            it.setVisible(true);
        }
        else
             JOptionPane.showMessageDialog(null,"Los dividendos por resultado exacto ya han sido asignados", "ERROR",JOptionPane.ERROR_MESSAGE);
    
}//GEN-LAST:event_buttonExactoActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    
}//GEN-LAST:event_formInternalFrameActivated

private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
    
}//GEN-LAST:event_formInternalFrameDeiconified

private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    
}//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExacto;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    private int idPart,idComp;
    private Tarea1 parent;
    private IControladorCompeticiones icc;
    
}
