/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfirmarFinalizar.java
 *
 * Created on 24/08/2011, 12:34:21 AM
 */

package Formularios;

import DataTypes.*;
import Interface.IControladorCompeticiones;
import Excepciones.ExDatosNoAsignados;
import java.util.List;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author santiago
 */
public class ConfirmarFinalizar extends javax.swing.JInternalFrame {

    /** Creates new form ConfirmarFinalizar */
    public ConfirmarFinalizar(Tarea1 parent, IControladorCompeticiones icc) {
        initComponents();

        this.icCompeticiones = icc;

        this.parent = parent;
        parent.setModoActivado(false);//no hace falta

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);

        //Fabrica f = new Fabrica();
        //IControladorCompeticiones icc = f.getIControladorCompeticiones();

        try {
            DataResumen dataR = icCompeticiones.listarIngresos();

            if(dataR.getpenalLocal()==dataR.getpenalVisita()){
                 this.Llocal.setText(dataR.getGolesLocal()+" ");
                 this.Lvisita.setText(dataR.getGolesVisita()+" ");
            }
             else{
                 this.Llocal.setText(dataR.getGolesLocal()+" - "+dataR.getpenalLocal());
                 this.Lvisita.setText(dataR.getGolesLocal()+" - "+dataR.getpenalVisita());
            }


            String[] colL = {"Id", "Nombre"};
            String[] colV = {"Id", "Nombre"};
            List<DataIdNombre> lisL=dataR.getJugadoresLocal();
            List<DataIdNombre> lisV=dataR.getJugadoresVisita();

            Object[][] dataL= new Object[lisL.size()][2];
            for (int i = 0;i<lisL.size();i++){
                 DataIdNombre c = (DataIdNombre) lisL.get(i);
                 dataL[i][0] = c.getId();
                 dataL[i][1] = c.getNombre();
            }
            TableModel dtm1 = new DefaultTableModel(dataL,colL);
            this.tablaJugEqLocal.setModel(dtm1);

            Object[][] dataV= new Object[lisV.size()][2];
            for (int i = 0;i<lisV.size();i++){
                 DataIdNombre cv = (DataIdNombre) lisV.get(i);
                 dataV[i][0] = cv.getId();
                 dataV[i][1] = cv.getNombre();
            }
            TableModel dtm2= new DefaultTableModel(dataV,colV);
            this.tablaJugEqVis.setModel(dtm2);
        }
        catch (ExDatosNoAsignados exc) {
            JOptionPane.showMessageDialog(null,exc.getMessage(),"ERROR", JOptionPane.ERROR_MESSAGE);
            icCompeticiones.finalizarVerDetallesComp();
            parent.setModoActivado(true);
            this.dispose();
        }
        catch (Exception exc) {
            JOptionPane.showMessageDialog(null,exc.getMessage(),"ERROR", JOptionPane.ERROR_MESSAGE);
            icCompeticiones.finalizarVerDetallesComp();
            parent.setModoActivado(true);
            this.dispose();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaJugEqLocal = new javax.swing.JTable();
        Confirmar = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaJugEqVis = new javax.swing.JTable();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Llocal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lvisita = new javax.swing.JLabel();

        jLabel50.setText("Jugadores Equipo Local ");

        jLabel52.setText("Jugadores Equipo Visitante ");

        tablaJugEqLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tablaJugEqLocal);

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        tablaJugEqVis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tablaJugEqVis);

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        jLabel1.setText("Goles");

        Llocal.setText("jLabel2");

        jLabel3.setText("Goles");

        Lvisita.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Confirmar)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(Llocal))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Lvisita))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jLabel52)
                    .addComponent(jLabel3)
                    .addComponent(Lvisita)
                    .addComponent(jLabel1)
                    .addComponent(Llocal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmar)
                    .addComponent(cancelar))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        //Fabrica f = new Fabrica();
        parent.setModoActivado(true);
        //IControladorCompeticiones icc = f.getIControladorCompeticiones();
        try{
            icCompeticiones.confirmarIngreso(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error "+e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        JOptionPane.showMessageDialog(null,"Se ha finalizado correctamente","Finalizar Partido", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_ConfirmarActionPerformed

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        // TODO add your handling code here:
        //Fabrica f = new Fabrica();
        parent.setModoActivado(true);
        //IControladorCompeticiones icc = f.getIControladorCompeticiones();
        try{
            icCompeticiones.confirmarIngreso(false);
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,"Error "+e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel Llocal;
    private javax.swing.JLabel Lvisita;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tablaJugEqLocal;
    private javax.swing.JTable tablaJugEqVis;
    // End of variables declaration//GEN-END:variables
    private Tarea1 parent;

    private IControladorCompeticiones icCompeticiones;
}
