/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DetallesJugador.java
 *
 * Created on 23/08/2011, 11:24:42 PM
 */

package Formularios;

/**
 *
 * @author santiago
 */
import DataTypes.DataJugador;
import javax.swing.ImageIcon;

public class DetallesJugador extends javax.swing.JInternalFrame {

    /** Creates new form DetallesJugador */
    public DetallesJugador(DataJugador j,Tarea1 parent) {
        initComponents();

        this.parent = parent;
        parent.setModoActivado(false);//no hace falta

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);

        //cargamos el datajugador en el formulario

    enombre.setText(enombre.getText().concat(j.getNombre()));
    enombrecompleto.setText(enombrecompleto.getText().concat(j.getNombreCompleto()));
    eedad.setText(eedad.getText().concat(Integer.toString(j.getEdad())));
    eposicion.setText(eposicion.getText().concat(j.getPosicion().toString()));
    elugar.setText(elugar.getText().concat(j.getLugarNacimiento()));
    efecha.setText(efecha.getText().concat(j.getFechaDeNacimiento().toString()));
    epeso.setText(epeso.getText().concat(Double.toString(j.getPeso())));
    ealtura.setText(ealtura.getText().concat(Double.toString(j.getAltura())));
    eid.setText(eid.getText().concat(Integer.toString(j.getId())));

    //cargamos la foto en el label
    String pathImage = j.getPathImage();

    if (pathImage.equals("")){
            jLabel11.setText("sin imagen");
    }else{
        ImageIcon image;
        try{
            image = new ImageIcon(pathImage);

            jLabel11.setText("");
            if(image.getIconHeight()>128 || image.getIconWidth()>128){
                int a = image.getIconWidth()-128;
                int b = image.getIconHeight() - 128;
                int razon = a ;
                if (a < b)
                    razon = b;
                ImageIcon imageScalada = new ImageIcon(image.getImage().getScaledInstance(image.getIconWidth()-razon, image.getIconHeight()-razon, 128));
                jLabel11.setIcon(imageScalada);

            }else{
               jLabel11.setIcon(image);
            }
        }catch (Exception e2){
            jLabel11.setText("Error al cargar");
        }
    }
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        enombre = new javax.swing.JLabel();
        enombrecompleto = new javax.swing.JLabel();
        efecha = new javax.swing.JLabel();
        elugar = new javax.swing.JLabel();
        eedad = new javax.swing.JLabel();
        eposicion = new javax.swing.JLabel();
        eid = new javax.swing.JLabel();
        ealtura = new javax.swing.JLabel();
        epeso = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setTitle("Detalles Jugador");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles Jugador"));

        enombre.setText("Nombre:");

        enombrecompleto.setText("Nombre Completo: ");

        efecha.setText("Fecha Nacimiento: ");

        elugar.setText("Lugar: ");

        eedad.setText("Edad: ");

        eposicion.setText("Posicion: ");

        eid.setText("Id: ");

        ealtura.setText("Altura: ");

        epeso.setText("Peso: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eposicion)
                    .addComponent(eedad)
                    .addComponent(elugar)
                    .addComponent(efecha)
                    .addComponent(enombrecompleto)
                    .addComponent(enombre)
                    .addComponent(eid)
                    .addComponent(ealtura)
                    .addComponent(epeso))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(eid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enombrecompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(efecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eedad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eposicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ealtura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epeso)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton8.setText("Aceptar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel11.setText("sin imagen");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jButton8)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        parent.setModoActivado(true);
        this.dispose();
}//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ealtura;
    private javax.swing.JLabel eedad;
    private javax.swing.JLabel efecha;
    private javax.swing.JLabel eid;
    private javax.swing.JLabel elugar;
    private javax.swing.JLabel enombre;
    private javax.swing.JLabel enombrecompleto;
    private javax.swing.JLabel epeso;
    private javax.swing.JLabel eposicion;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    private Tarea1 parent;
}
