/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IngresoEventos.java
 *
 * Created on 12/10/2011, 01:47:22 AM
 */

package Formularios;

/**
 *
 * @author Santiago
 */
import Excepciones.*;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class IngresoEventos extends javax.swing.JInternalFrame {

    /** Creates new form IngresoEventos */
    public IngresoEventos(Tarea1 parent,Interface.IControladorCompeticiones icCompeticiones) {
        initComponents();

        this.icCompeticiones = icCompeticiones;

        this.parent = parent;
        parent.setModoActivado(false);//no hace falta

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);


        try {
            DataTypes.DataResumen d = icCompeticiones.listarIngresos();

            this.dataR = d;

            this.golesLocal = dataR.getGolesLocal();
            this.golesvisita = dataR.getGolesVisita();

            if(dataR.getpenalLocal()==dataR.getpenalVisita()){
                 this.labelres.setText(dataR.getGolesLocal()+" a " + dataR.getGolesVisita());
                 
            }
             else{
                this.labelres.setText(dataR.getGolesLocal()+ "("+dataR.getGolesLocal()+")"+ "a" + dataR.getGolesVisita()+ "("+dataR.getGolesVisita()+")");
            }


            String[] colL = {"Id", "Nombre"};
            String[] colV = {"Id", "Nombre"};
            java.util.List<DataTypes.DataIdNombre> lisL=dataR.getJugadoresLocal();
            java.util.List<DataTypes.DataIdNombre> lisV=dataR.getJugadoresVisita();

            Object[][] dataL= new Object[lisL.size()][2];
            for (int i = 0;i<lisL.size();i++){
                 DataTypes.DataIdNombre c = (DataTypes.DataIdNombre) lisL.get(i);
                 dataL[i][0] = c.getId();
                 dataL[i][1] = c.getNombre();
            }
            TableModel dtm1 = new DefaultTableModel(dataL,colL);
            this.tablaJugEqLocal.setModel(dtm1);

            Object[][] dataV= new Object[lisV.size()][2];
            for (int i = 0;i<lisV.size();i++){
                 DataTypes.DataIdNombre cv = (DataTypes.DataIdNombre) lisV.get(i);
                 dataV[i][0] = cv.getId();
                 dataV[i][1] = cv.getNombre();
            }
            TableModel dtm2= new DefaultTableModel(dataV,colV);
            this.tablaJugEqVis.setModel(dtm2);
        }
        catch (ExDatosNoAsignados exc) {
            JOptionPane.showMessageDialog(null,exc.getMessage(),"ERROR", JOptionPane.ERROR_MESSAGE);
            icCompeticiones.finalizarVerDetallesComp();
            parent.setModoActivado(true);
            this.dispose();
        }
        catch (Exception exc) {
            JOptionPane.showMessageDialog(null,exc.getMessage(),"ERROR", JOptionPane.ERROR_MESSAGE);
            icCompeticiones.finalizarVerDetallesComp();
            parent.setModoActivado(true);
            this.dispose();
        }

        jLabel5.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaJugEqLocal = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Gol = new javax.swing.JRadioButton();
        Sustitucion = new javax.swing.JRadioButton();
        TarjetaRoja = new javax.swing.JRadioButton();
        TarjetaAmarilla = new javax.swing.JRadioButton();
        labelSeleccioneJug = new javax.swing.JLabel();
        labelNomJugador1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNomJugador2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JRadioButton();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaJugEqVis = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        labelres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();

        setTitle("Agregar Eventos");

        tablaJugEqLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaJugEqLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJugEqLocalMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaJugEqLocal);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Evento"));

        agregar.setText("Agregar Evento");
        agregar.setEnabled(false);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Evento:");

        buttonGroup1.add(Gol);
        Gol.setSelected(true);
        Gol.setText("Gol");
        Gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolActionPerformed(evt);
            }
        });

        buttonGroup1.add(Sustitucion);
        Sustitucion.setText("Sustitucion");
        Sustitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SustitucionActionPerformed(evt);
            }
        });

        buttonGroup1.add(TarjetaRoja);
        TarjetaRoja.setText("Tarjeta Roja");
        TarjetaRoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaRojaActionPerformed(evt);
            }
        });

        buttonGroup1.add(TarjetaAmarilla);
        TarjetaAmarilla.setText("Tarjeta Amarrila");
        TarjetaAmarilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaAmarillaActionPerformed(evt);
            }
        });

        labelSeleccioneJug.setText("Seleccione un jugador:");

        labelNomJugador1.setText("  ");

        jLabel5.setText("por");

        labelNomJugador2.setText("  ");

        jButton1.setText("Cancelar Evento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Minuto:");

        m.setText("00");

        jLabel7.setText("Periodo:");

        buttonGroup2.add(t1);
        t1.setSelected(true);
        t1.setText("1er tiempo");

        buttonGroup2.add(t2);
        t2.setText("2do tiempo");

        buttonGroup2.add(a1);
        a1.setText("1er alargue");

        buttonGroup2.add(a2);
        a2.setText("2do alargue");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(agregar)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sustitucion)
                                    .addComponent(Gol)
                                    .addComponent(TarjetaRoja)
                                    .addComponent(TarjetaAmarilla))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSeleccioneJug)
                                    .addComponent(jLabel5)
                                    .addComponent(labelNomJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(labelNomJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t2)
                                        .addComponent(t1)
                                        .addComponent(a1)
                                        .addComponent(a2))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sustitucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TarjetaRoja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TarjetaAmarilla)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelSeleccioneJug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomJugador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomJugador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jLabel2.setText("Jugadores Local");

        jLabel3.setText("Resultado del partido:");

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tablaJugEqVis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaJugEqVis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJugEqVisMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaJugEqVis);

        jLabel4.setText("Jugadores Visitante");

        labelres.setText("jLabel5");

        log.setColumns(20);
        log.setEditable(false);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelres)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelres))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarform(){
    //despejamos el formulario.

        
        this.labelNomJugador1.setText("");
        this.labelNomJugador2.setText("");
        this.jLabel5.setVisible(false);
        this.agregar.setEnabled(false);
        this.idSeleccionadoTabla1=-1;
        this.idSeleccionadoTabla2=-1;

        this.tablaJugEqVis.setVisible(true);
        this.tablaJugEqLocal.setVisible(true);
        //
    }
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:

        //insertamos el evento siempre cuando no salte alguna excepcion

        //creamos el data evento.
        DataTypes.TipoPeriodo tipo = null;
        DataTypes.TipoEvento tipoE = null;
        boolean amarilla = false;

        if (this.Gol.isSelected())
            tipoE = DataTypes.TipoEvento.Gol;
        if (this.Sustitucion.isSelected())
            tipoE = DataTypes.TipoEvento.Sustitucion;
        if (this.TarjetaRoja.isSelected()){
            tipoE = DataTypes.TipoEvento.Tarjeta;
            amarilla = false;
        }
        if (this.TarjetaAmarilla.isSelected()){
            tipoE = DataTypes.TipoEvento.Tarjeta;
            amarilla = true;
        }
        DataTypes.TipoPeriodo tipoP=null;
        if (this.t1.isSelected())
            tipoP = DataTypes.TipoPeriodo.PrimerTiempo;
        if (this.t2.isSelected())
            tipoP = DataTypes.TipoPeriodo.SegundoTiempo;
        if (this.a1.isSelected())
            tipoP = DataTypes.TipoPeriodo.PrimerAlargue;
        if (this.a2.isSelected())
            tipoP = DataTypes.TipoPeriodo.SegundoAlargue;
        
        java.util.List<DataTypes.DataIdNombre> listL = this.dataR.getJugadoresLocal();
        java.util.List<DataTypes.DataIdNombre> listV = this.dataR.getJugadoresVisita();

        //buscamos el jugador 1
        DataTypes.DataIdNombre j1=null;
        DataTypes.DataIdNombre j2=null;
        boolean encontre = false;

        for(DataTypes.DataIdNombre da :listL){
            if (da.getId()==this.idSeleccionadoTabla1){
                j1 = new DataTypes.DataIdNombre(da.getId(),da.getNombre(),null);
                encontre = true;
            }
            if (tipoE == DataTypes.TipoEvento.Sustitucion){
                if (da.getId()==this.idSeleccionadoTabla2){
                j2 = new DataTypes.DataIdNombre(da.getId(),da.getNombre(),null);
            }
            }
        }
        if (!encontre){
            for(DataTypes.DataIdNombre da :listV){
                if (da.getId()==this.idSeleccionadoTabla1){
                    j1 = new DataTypes.DataIdNombre(da.getId(),da.getNombre(),null);
                }
                if (tipoE == DataTypes.TipoEvento.Sustitucion){
                    if (da.getId()==this.idSeleccionadoTabla2){
                        j2 = new DataTypes.DataIdNombre(da.getId(),da.getNombre(),null);
                }
                }
             }
        }

        int minuto;

        try{
            minuto = Integer.parseInt(m.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE );
            return;
        }

        DataTypes.DataEvento datae = new DataTypes.DataEvento(minuto,tipoP,j1,j2,tipoE,amarilla);
        //creamos el datae, y luego mandamos a la operacion de sistema


        //controlamos que no ponga goles donde no debe
        if (this.Gol.isSelected()){
            boolean error =false;
            if (esLocal){
                if (this.golesLocal== 0){
                    error = true;
                }
            }else{
                if (this.golesvisita== 0){
                    error = true;
                }
            }
            if (error){
                JOptionPane.showMessageDialog(null, "Error: No se pueden agrear mas goles para este equipo","Error", JOptionPane.ERROR_MESSAGE );
                return;
            }

            if (esLocal){
                this.golesLocal=this.golesLocal-1;
            }else{
                this.golesvisita=this.golesvisita-1;
            }
        }
      
        try{
            icCompeticiones.ingresarEventos(datae);        
            log.setText(log.getText()+"Evento: "+tipoE.toString()+" periodo: " + tipoP.toString()+"Minuto:" + minuto + "\n");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE );
        }

        limpiarform();

    }//GEN-LAST:event_agregarActionPerformed

    private void GolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolActionPerformed
        limpiarform();
    }//GEN-LAST:event_GolActionPerformed

    private void tablaJugEqVisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJugEqVisMouseClicked
        // TODO add your handling code here:

       fila = tablaJugEqVis.rowAtPoint(evt.getPoint());//es global
       columna = tablaJugEqVis.columnAtPoint(evt.getPoint());

       if ((fila > -1) && (columna > -1)){
            if (this.Sustitucion.isSelected()){
                if (!this.seleccionJug2){
                    idSeleccionadoTabla1 = (Integer) tablaJugEqVis.getValueAt(fila,0);
                    this.labelNomJugador1.setText((String)tablaJugEqVis.getValueAt(fila,1));
                    //habilitamos para que luego seleccione el segundo jugador

                    this.jLabel5.setVisible(true);
                    this.jLabel5.setText("Entra por:");
                    this.seleccionJug2=true; //para que el proximo jugador a seleccionar sea el jugador saliente

                    this.tablaJugEqLocal.setVisible(false); //desabilitamos la otra tabla, para que solo agrege de un lado la sustitucion

                }else{
                    idSeleccionadoTabla2 = (Integer) tablaJugEqVis.getValueAt(fila,0);
                    this.labelNomJugador2.setText((String)tablaJugEqVis.getValueAt(fila,1));
                    
                    agregar.setEnabled(true);

                    this.seleccionJug2 = false;
                }
            }else{
                idSeleccionadoTabla1 = (Integer) tablaJugEqVis.getValueAt(fila,0);
                this.labelNomJugador1.setText((String)tablaJugEqVis.getValueAt(fila,1));
                agregar.setEnabled(true);
                this.esLocal=false;
            }
        }
}//GEN-LAST:event_tablaJugEqVisMouseClicked

    private void tablaJugEqLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJugEqLocalMouseClicked
        // TODO add your handling code here:
       fila = tablaJugEqLocal.rowAtPoint(evt.getPoint());//es global
       columna = tablaJugEqLocal.columnAtPoint(evt.getPoint());

       if ((fila > -1) && (columna > -1)){
            if (this.Sustitucion.isSelected()){
                if (!this.seleccionJug2){//si esta para seleccionar el primero...
                    idSeleccionadoTabla1 = (Integer) tablaJugEqLocal.getValueAt(fila,0);
                    this.labelNomJugador1.setText((String)tablaJugEqLocal.getValueAt(fila,1));
                    //habilitamos para que luego seleccione el segundo jugador

                    this.jLabel5.setVisible(true);
                    this.jLabel5.setText("Entra por:");
                    this.seleccionJug2=true; //para que el proximo jugador a seleccionar sea el jugador saliente

                    this.tablaJugEqVis.setVisible(false); //desabilitamos la otra tabla, para que solo agrege de un lado la sustitucion

                }else{
                    idSeleccionadoTabla2 = (Integer) tablaJugEqLocal.getValueAt(fila,0);
                    this.labelNomJugador2.setText((String)tablaJugEqLocal.getValueAt(fila,1));
                    
                    agregar.setEnabled(true);

                    this.seleccionJug2 = false;
                }
            }else{
                idSeleccionadoTabla1 = (Integer) tablaJugEqLocal.getValueAt(fila,0);
                this.labelNomJugador1.setText((String)tablaJugEqLocal.getValueAt(fila,1));
                agregar.setEnabled(true);
                this.esLocal = true;
            }
        }
        
}//GEN-LAST:event_tablaJugEqLocalMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        if ((this.golesLocal!=0)||(this.golesvisita!=0)){
                JOptionPane.showMessageDialog(null, "Error: Faltan agregar goles","Error", JOptionPane.ERROR_MESSAGE );
                return;
        }else{
            icCompeticiones.confirmarEventos(); //agrega los eventos al dataresumen
            
            javax.swing.JInternalFrame j = new ConfirmarFinalizar(parent,icCompeticiones);
            parent.getLayeredPane().add(j);
            j.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        parent.setModoActivado(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SustitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SustitucionActionPerformed
        // TODO add your handling code here:
        limpiarform();
    }//GEN-LAST:event_SustitucionActionPerformed

    private void TarjetaRojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaRojaActionPerformed
        // TODO add your handling code here:
        limpiarform();
    }//GEN-LAST:event_TarjetaRojaActionPerformed

    private void TarjetaAmarillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaAmarillaActionPerformed
        // TODO add your handling code here:
        limpiarform();
    }//GEN-LAST:event_TarjetaAmarillaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiarform();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Gol;
    private javax.swing.JRadioButton Sustitucion;
    private javax.swing.JRadioButton TarjetaAmarilla;
    private javax.swing.JRadioButton TarjetaRoja;
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JButton agregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelNomJugador1;
    private javax.swing.JLabel labelNomJugador2;
    private javax.swing.JLabel labelSeleccioneJug;
    private javax.swing.JLabel labelres;
    private javax.swing.JTextArea log;
    private javax.swing.JTextField m;
    private javax.swing.JRadioButton t1;
    private javax.swing.JRadioButton t2;
    private javax.swing.JTable tablaJugEqLocal;
    private javax.swing.JTable tablaJugEqVis;
    // End of variables declaration//GEN-END:variables
    private Interface.IControladorCompeticiones icCompeticiones;
    private Tarea1 parent;
    private int fila,columna;

    private DataTypes.DataResumen dataR;

    private int idSeleccionadoTabla1=-1;//valor que esta seleccionado en la tabla
    private int idSeleccionadoTabla2=-1;//valor que esta seleccionado en la tabla, por el que sale en caso de sustitucion

    private int golesLocal; //mantiene los goles de local que faltan agregar
    private int golesvisita; //los goles visitante que faltan agregar como eventos gol
    
    private boolean esLocal;

    private boolean seleccionJug2=false;
}
