/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListarUsuarios.java
 *
 * Created on 04-sep-2011, 20:18:20
 */

package Formularios;

import Interface.Fabrica;
import Interface.IAdminUsuarios;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author CAPablito
 */
public class ListarUsuarios extends javax.swing.JInternalFrame {

    /** Creates new form ListarUsuarios */
    public ListarUsuarios(Tarea1 parent) {
        this.parent = parent;
        this.parent.setModoActivado(false);

        initComponents();


        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);


        jButton1.setEnabled(false);


        Fabrica f = new Fabrica();
        this.icu = f.getIAdminUsuarios();
        try {

            List<String> lista = icu.listarNickUsuarios();
            System.out.println("Luego de listar, tam:"+lista.size());
            String [] s = {"Nick"};
            Object[][] tabla = new Object[lista.size()][1];
            for (int i =0;i< lista.size();i++) {
                tabla[i][0]= lista.get(i);
            }
            TableModel dtm = new DefaultTableModel(tabla,s);            
            TablaUsuariosRegistrados.setModel(dtm);
        }
        catch (Exception exc){
            javax.swing.JOptionPane.showMessageDialog(null, "Error: "+ exc.getMessage(),"Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            parent.setModoActivado(true);
        }
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuariosRegistrados = new javax.swing.JTable()
        {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Usuarios Registrados");

        TablaUsuariosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaUsuariosRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosRegistradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuariosRegistrados);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DetallesUsuario du = new DetallesUsuario(nick,parent,this.icu);
        parent.getLayeredPane().add(du);
        //parent.getContentPane().add(du);
        du.setVisible(true);

       

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaUsuariosRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosRegistradosMouseClicked
        // TODO add your handling code here:

        fila = this.TablaUsuariosRegistrados.rowAtPoint(evt.getPoint());
        columna = this.TablaUsuariosRegistrados.columnAtPoint(evt.getPoint());

        if ((fila > -1) && (columna > -1)){
            nick = (String) this.TablaUsuariosRegistrados.getValueAt(fila,0);

            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_TablaUsuariosRegistradosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        parent.setModoActivado(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsuariosRegistrados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private Tarea1 parent;
    private int fila,columna;
    private String nick;

    private IAdminUsuarios icu;
}
