/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListaPartidoDivNoAsignado.java
 *
 * Created on 24/08/2011, 12:34:57 AM
 */

package Formularios;

import Interface.Fabrica;
import Interface.IControladorCompeticiones;
import DataTypes.DataInfoPartido;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import javax.swing.table.TableModel;

/**
 *
 * @author santiago
 */
public class ListaPartidoDivNoAsignado extends javax.swing.JInternalFrame {

    /** Creates new form ListaPartidoDivNoAsignado */
    public ListaPartidoDivNoAsignado(Tarea1 parent) {
        initComponents();

        this.parent = parent;
        parent.setModoActivado(false);

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);


        jButton24.setEnabled(false);
        Fabrica f = new Fabrica();
        this.icCompeticiones = f.getIControladorCompeticiones();
        try {
            List<DataInfoPartido> lista = icCompeticiones.listarPartidosDivNoAsig();
            String [] s = {"Fecha","Id Competencia","Nombre Competencia","Id Partido","Equipo Local","Equipo Visitante", "Lugar"};
            Object[][] tabla = new Object[lista.size()][7];
            for (int i =0;i< lista.size();i++) {
                DataInfoPartido d = lista.get(i);
                tabla[i][0]=  d.getFechaHora();
                tabla[i][1] = d.getIdComp();
                tabla[i][2] = d.getNomComp();
                tabla[i][3] = d.getIdPar();
                tabla[i][4] = d.getNomLocal();
                tabla[i][5] = d.getNomVisita();
                tabla[i][6] = d.getLugar();
            }
            TableModel dtm = new DefaultTableModel(tabla,s);
            TablaPartidosDivNoAsignados.setModel(dtm);
        }
        catch (Exception exc){
            javax.swing.JOptionPane.showMessageDialog(null, "Error: "+ exc.getMessage(),"Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            parent.setModoActivado(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton25 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TablaPartidosDivNoAsignados = new javax.swing.JTable()
        {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        setTitle("Asignar Dividendos A Partido");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jButton25.setText("Cancelar");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton24.setText("Aceptar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jLabel54.setText("Partidos Sin Dividendos Asignados");

        TablaPartidosDivNoAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaPartidosDivNoAsignados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaPartidosDivNoAsignados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPartidosDivNoAsignadosMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(TablaPartidosDivNoAsignados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                                .addComponent(jButton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton25)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addContainerGap(334, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24)
                    .addComponent(jButton25))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
       AsignarDividendos s = new AsignarDividendos(idComp,idPart,parent,icCompeticiones);

       parent.getLayeredPane().add(s);
       s.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void TablaPartidosDivNoAsignadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPartidosDivNoAsignadosMouseClicked
        // TODO add your handling code here:
        fila = this.TablaPartidosDivNoAsignados.rowAtPoint(evt.getPoint());
        columna = this.TablaPartidosDivNoAsignados.columnAtPoint(evt.getPoint());

        if ((fila > -1) && (columna > -1)){
            idComp = (Integer) this.TablaPartidosDivNoAsignados.getValueAt(fila,1);
            idPart = (Integer) this.TablaPartidosDivNoAsignados.getValueAt(fila,3);

            jButton24.setEnabled(true);
        }
    }//GEN-LAST:event_TablaPartidosDivNoAsignadosMouseClicked

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        parent.setModoActivado(true);
        this.dispose();
    }//GEN-LAST:event_jButton25ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPartidosDivNoAsignados;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JScrollPane jScrollPane12;
    // End of variables declaration//GEN-END:variables
    private int fila,columna,idComp,idPart;
    private Tarea1 parent;

    private IControladorCompeticiones icCompeticiones;
}
