/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SeleccionJugadoresFinalizar.java
 *
 * Created on 24/08/2011, 12:32:12 AM
 */

package Formularios;


/**
 *
 * @author santiago
 */

import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import java.util.List;
import DataTypes.*; //casi todos
import Interface.Fabrica;
import Interface.IControladorEquipos;
import Interface.IControladorCompeticiones;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import DataTypes.TipoCompeticion;

public class SeleccionJugadoresFinalizar extends javax.swing.JInternalFrame {

    /** Creates new form SeleccionJugadoresFinalizar */
    public SeleccionJugadoresFinalizar(Tarea1 parent,int idLocal,int idVisita, IControladorCompeticiones icc) {
        initComponents();

        this.icCompeticiones = icc;

        this.parent = parent;
        parent.setModoActivado(false);

        java.awt.Component content = parent.getContentPane();
        int x = (content.getWidth() - this.getWidth()) / 2;
        int y = (content.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);

        // tipoC = tipo;
        this.indiceEquipo=idLocal;
        idV=idVisita;
        this.listaEquiposSeleccionados = new ArrayList<DataIdNombre>();
        siguiente.setEnabled(false);
        agregar.setEnabled(false);
        agregar.setText("Agregar Local");
        TableModel modelo = null; //lo armamos segun la operacion

        //Fabrica f =  new Fabrica();
        String[] columnas = {"Id", "Nombre"};
        Object[][] data=null;

        //IControladorCompeticiones icc = f.getIControladorCompeticiones();
        List<DataIdNombre> lista = icCompeticiones.listaJugadores();
        data= new Object[lista.size()][2];
        for (int i = 0;i<lista.size();i++){
            DataIdNombre e = (DataIdNombre) lista.get(i);
            data[i][0] = e.getId();
            data[i][1] = e.getNombre();
        }
        modelo = new DefaultTableModel(data,columnas);
        tablaSeleccion.setModel(modelo);
        this.setTitle("Selecciones los jugadores");
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        tablaSeleccion.setRowSorter(sorter);

        filtro.addKeyListener(new KeyListener() {

        @Override
        public void keyTyped(KeyEvent arg0) {
            String i = "(?i)";
            String texto= i.concat(filtro.getText());

            if (texto.length() == 4) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter(texto));
            }
        }
        @Override
        public void keyReleased(KeyEvent arg0) {
            String i = "(?i)";
            String texto= i.concat(filtro.getText());
             if (texto.length() == 4) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter(texto,1));
            }
        }
        @Override
        public void keyPressed(KeyEvent arg0) {
            String i = "(?i)";
            String texto= i.concat(filtro.getText());

            if (texto.length() == 4) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter(texto,1));
            }

                }
                });

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaSeleccion = new javax.swing.JTable();
        filtro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Seleccion Jugadores");

        agregar.setText("Agregar al local");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        jButton14.setText("Cancelar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        tablaSeleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSeleccionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaSeleccion);

        filtro.setColumns(4);
        filtro.setFont(new java.awt.Font("DejaVu Sans", 2, 13));
        filtro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtroMouseClicked(evt);
            }
        });

        jLabel1.setText("Selecciones un jugador y presione, agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton14)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(agregar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        //Fabrica f = new Fabrica();
        //IControladorCompeticiones icc = f.getIControladorCompeticiones();
        DefaultTableModel temp;
     try {
            icCompeticiones.ingresarJugador(this.idSeleccionadoTabla, indiceEquipo);
            temp = (DefaultTableModel) tablaSeleccion.getModel();
            temp.removeRow(fila);
        }
       catch(Exception e){

        }
        agregar.setEnabled(false);
        siguiente.setEnabled(true);

//                        ListaJugadores.setVisible(false)                
}//GEN-LAST:event_agregarActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        siguiente.setEnabled(false);
        if(this.indiceEquipo!=idV){
           this.indiceEquipo=idV;
           agregar.setText("Agregar visitante");
        }
         else{
             JInternalFrame j = new IngresoEventos(parent,icCompeticiones);
             parent.getLayeredPane().add(j);
             j.setVisible(true);
             this.dispose(); 
         }
}//GEN-LAST:event_siguienteActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        //Fabrica f =  new Fabrica();
        parent.setModoActivado(true);
        
        //IControladorCompeticiones iCC= f.getIControladorCompeticiones();
        icCompeticiones.limpiarMemoriaAuxiliar();
        this.dispose();
}//GEN-LAST:event_jButton14ActionPerformed

    private void filtroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroMouseClicked

    private void tablaSeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSeleccionMouseClicked
        // TODO add your handling code here:
        fila = tablaSeleccion.rowAtPoint(evt.getPoint());//es global
        int columna = tablaSeleccion.columnAtPoint(evt.getPoint());

        if ((fila > -1) && (columna > -1)){
            idSeleccionadoTabla = (Integer) tablaSeleccion.getValueAt(fila,0);
            nombreSeleccionadoTabla = (String) tablaSeleccion.getValueAt(fila,1);
            agregar.setEnabled(true);
        }
    }//GEN-LAST:event_tablaSeleccionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField filtro;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton siguiente;
    private javax.swing.JTable tablaSeleccion;
    // End of variables declaration//GEN-END:variables
    private JDesktopPane escritorio;
    List<DataIdNombre> listaEquiposSeleccionados = null;

    private int idSeleccionadoTabla,fila;
    private String nombreSeleccionadoTabla;
    private TipoCompeticion tipoC=null;
    private int indiceEquipo,idV;
    private Tarea1 parent;

    private IControladorCompeticiones icCompeticiones;
}
