
package WebServices.DispMovilWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DispMovilWS", targetNamespace = "http://WebServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DispMovilWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean iniciarSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void ingresarSaldoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        float arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean participarEnPenca(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void confirmarParticipacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void cerrarSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.ListBeanDataInfoPartido
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanDataInfoPartido obtenerPartidosNoFinalizadosPenca(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarPartidoPenca(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void enviarMensaje(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        boolean arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns WebServices.DispMovilWS.ListBeanDataIdNombre
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanDataIdNombre listarCompetencias();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.DataCompeticion
     * @throws ExNoExisteCompeticion_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataCompeticion verInfoCompeticion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExNoExisteCompeticion_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void finalizarVerDetallesComp(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.DataUsuario
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataUsuario verPerfilUsuarioLogueado(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.ListBeanApuesta
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanApuesta mostrarHistorialApuestas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DataFechaHora arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DataFechaHora arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ExCompeticionFinalizada_Exception
     * @throws ExDivsNoAsignados_Exception
     * @throws ExNoExisteCompeticion_Exception
     */
    @WebMethod
    public void seleccionarCompeticion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExCompeticionFinalizada_Exception, ExDivsNoAsignados_Exception, ExNoExisteCompeticion_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void seleccionarCampApuesta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        TipoCampeonatoApuesta arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ExPartidoCampInvalido_Exception
     * @throws Exception_Exception
     * @throws ExDivsNoAsignados_Exception
     */
    @WebMethod
    public void seleccionarPartidoCamp(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExDivsNoAsignados_Exception, ExPartidoCampInvalido_Exception, Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarPartido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        TipoDividendo arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarCampeonato(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarGoleador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarResultadoExacto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        float arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.DataApuestaWS
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataApuestaWS mostrarApuesta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void confirmarAltaApuesta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1,
        @WebParam(name = "arg2", partName = "arg2")
        boolean arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.DataInfoPenca
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataInfoPenca verTablaPosicionesPenca(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void crearPaqueteApuestas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.DataPaqueteApuestasWS
     * @throws ExPaqueteNoActivado_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataPaqueteApuestasWS mostrarPaqueteApuestas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExPaqueteNoActivado_Exception, Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarPartidoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        TipoDividendo arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarCampeonatoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarGoleadorPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void apostarResultadoExactoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        float arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.DataApuestaWS
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataApuestaWS mostrarApuestaPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void agregarApuestaPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean validarPaqueteApuestas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void confirmarPaqueteApuestas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.ListBean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean verPaqueteApuestas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.ListBeanDataPartido
     * @throws ExDatosNoAsignados_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanDataPartido infoPartidosCompeticion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExDatosNoAsignados_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.ListBeanDataInfoPenca
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanDataInfoPenca obtenerInfoPencas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.DispMovilWS.ListBeanGoleadores
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanGoleadores obtenerJugadoresCampeonato(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws Exception_Exception
    ;

}
