
package WebServices.DispMovilWS;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ExCompeticionFinalizada", targetNamespace = "http://WebServices/")
public class ExCompeticionFinalizada_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExCompeticionFinalizada faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ExCompeticionFinalizada_Exception(String message, ExCompeticionFinalizada faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ExCompeticionFinalizada_Exception(String message, ExCompeticionFinalizada faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: WebServices.DispMovilWS.ExCompeticionFinalizada
     */
    public ExCompeticionFinalizada getFaultInfo() {
        return faultInfo;
    }

}
