
package WebServices.ImageServer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ImageServerService", targetNamespace = "http://WebServices/", wsdlLocation = "http://pcunix124:8280/imageServerWS?wsdl")
public class ImageServerService
    extends Service
{

    private final static URL IMAGESERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WebServices.ImageServer.ImageServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WebServices.ImageServer.ImageServerService.class.getResource(".");
            url = new URL(baseUrl, "http://pcunix124:8280/imageServerWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://pcunix124:8280/imageServerWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IMAGESERVERSERVICE_WSDL_LOCATION = url;
    }

    public ImageServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageServerService() {
        super(IMAGESERVERSERVICE_WSDL_LOCATION, new QName("http://WebServices/", "ImageServerService"));
    }

    /**
     * 
     * @return
     *     returns ImageServer
     */
    @WebEndpoint(name = "ImageServerPort")
    public ImageServer getImageServerPort() {
        return super.getPort(new QName("http://WebServices/", "ImageServerPort"), ImageServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageServer
     */
    @WebEndpoint(name = "ImageServerPort")
    public ImageServer getImageServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices/", "ImageServerPort"), ImageServer.class, features);
    }

}
