
package WebServices.MostrarFecha1;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MostrarFecha1", targetNamespace = "http://WebServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MostrarFecha1 {


    /**
     * 
     * @return
     *     returns WebServices.MostrarFecha1.DataFechaHora
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataFechaHora getFecha();

}
