
package WebServices.CompeticionesWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CompeticionesWS", targetNamespace = "http://WebServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompeticionesWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.DataPartido
     * @throws ExNoExistePartidoEnCompeticion_Exception
     * @throws ExNoExisteCompeticion_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataPartido seleccionarPartido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws ExNoExisteCompeticion_Exception, ExNoExistePartidoEnCompeticion_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBeanEquipo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanEquipo listarEquipos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBean
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean listaJugadores(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBean
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean listarCompetencias(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.DataJugador
     * @throws ExNoExisteJugador_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataJugador seleccionarJugador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExNoExisteJugador_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.DataCompeticion
     * @throws ExNoExisteCompeticion_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataCompeticion verInfoCompeticion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExNoExisteCompeticion_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void finalizarVerDetallesComp(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getImagePath(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void agregarCompeticionSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBeanDataPartidoComp
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanDataPartidoComp listarPartidos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ListBeanFiltro arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.FloatArrayArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public FloatArrayArray obtenerDividendosResultadoExacto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.DataJugPartido
     * @throws ExNoExisteCompeticion_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataJugPartido verInfoPartidoFinalizado(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExNoExisteCompeticion_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void finalizarDetallesPartido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBean
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean listarLigasDefinidas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBeanDataEquipoLiga
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanDataEquipoLiga obtenerTablaDePosiciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBean
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean obtenerUltimosPartidosFinalizados(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBean
     * @throws ExDatosNoAsignados_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean infoPartidosCompeticion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExDatosNoAsignados_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.DataJugPartido
     * @throws ExNoExistePartidoEnCompeticion_Exception
     * @throws ExDatosNoAsignados_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public DataJugPartido listarJugadoresPorBando(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExDatosNoAsignados_Exception, ExNoExistePartidoEnCompeticion_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBean
     * @throws ExNoExisteEquipo_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean listarJugEquipo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExNoExisteEquipo_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean competicionEstaFinalizada(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBean
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBean listarPencasDisponibles(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBeanGoleadores
     * @throws ExNoExisteCompeticion_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanGoleadores getJugadoresCampeonato(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExNoExisteCompeticion_Exception, Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns WebServices.CompeticionesWS.ListBeanGoleadores
     * @throws ExNoExisteCompeticion_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListBeanGoleadores get5MaxGoleadores(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws ExNoExisteCompeticion_Exception, Exception_Exception
    ;

}
