
package WebServices.CompeticionesWS;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ExNoExisteEquipo", targetNamespace = "http://WebServices/")
public class ExNoExisteEquipo_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExNoExisteEquipo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ExNoExisteEquipo_Exception(String message, ExNoExisteEquipo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ExNoExisteEquipo_Exception(String message, ExNoExisteEquipo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: WebServices.CompeticionesWS.ExNoExisteEquipo
     */
    public ExNoExisteEquipo getFaultInfo() {
        return faultInfo;
    }

}
