
package WebServices.RegistroAccesoWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RegistroAccesoWSService", targetNamespace = "http://WebServices/", wsdlLocation = "http://pcunix124:8280/registroAccesoWS?wsdl")
public class RegistroAccesoWSService
    extends Service
{

    private final static URL REGISTROACCESOWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WebServices.RegistroAccesoWS.RegistroAccesoWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WebServices.RegistroAccesoWS.RegistroAccesoWSService.class.getResource(".");
            url = new URL(baseUrl, "http://pcunix124:8280/registroAccesoWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://pcunix124:8280/registroAccesoWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REGISTROACCESOWSSERVICE_WSDL_LOCATION = url;
    }

    public RegistroAccesoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistroAccesoWSService() {
        super(REGISTROACCESOWSSERVICE_WSDL_LOCATION, new QName("http://WebServices/", "RegistroAccesoWSService"));
    }

    /**
     * 
     * @return
     *     returns RegistroAccesoWS
     */
    @WebEndpoint(name = "RegistroAccesoWSPort")
    public RegistroAccesoWS getRegistroAccesoWSPort() {
        return super.getPort(new QName("http://WebServices/", "RegistroAccesoWSPort"), RegistroAccesoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistroAccesoWS
     */
    @WebEndpoint(name = "RegistroAccesoWSPort")
    public RegistroAccesoWS getRegistroAccesoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices/", "RegistroAccesoWSPort"), RegistroAccesoWS.class, features);
    }

}
