
package WebServices.RegistroAccesoWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RegistroAccesoWS", targetNamespace = "http://WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistroAccesoWS {


    /**
     * 
     * @param browserSO
     * @param url
     * @param ip
     */
    @WebMethod
    @RequestWrapper(localName = "registrarAcceso", targetNamespace = "http://WebServices/", className = "WebServices.RegistroAccesoWS.RegistrarAcceso")
    @ResponseWrapper(localName = "registrarAccesoResponse", targetNamespace = "http://WebServices/", className = "WebServices.RegistroAccesoWS.RegistrarAccesoResponse")
    public void registrarAcceso(
        @WebParam(name = "browser_SO", targetNamespace = "")
        String browserSO,
        @WebParam(name = "ip", targetNamespace = "")
        String ip,
        @WebParam(name = "url", targetNamespace = "")
        String url);

}
